### ISSUE TITLE
Wrong link in rubygems

### ISSUE THREAD

**Issue by xaf** [kitop/ns1-ruby#3]
https://rubygems.org/gems/ns1/versions/0.2.0 links to https://github.com/kitop/ns1/ instead of https://github.com/kitop/ns1-ruby - Might want to correct that ?

**Comment by kitop** [comment]
Thanks! Fixed in https://github.com/kitop/ns1-ruby/commit/c0ca35d58d072861ac8f7061170f9f2fcaf4ae42

Will be updated with the next release :)
